# Copyright (c) 2016-2018, Linaro Limited
# All rights reserved.
# SPDX-License-Identifier:     BSD-3-Clause
#
# Please update xxxx for your coverity token and notification email if required
# pushing to github/master will run make check
# pushing to github/coverity_scan will also launch a static analysis
# See https://scan.coverity.com/travis_ci

#
# Travis uses Docker images which mainained here:
# 	https://github.com/Linaro/odp-docker-images
# CI scirpts are maintained under ./scripts/ci/ directory
# which passed into container during the test run.

language: c
sudo: required
dist: trusty
stages:
  - "build only"
  - test

addons:
        apt:
                packages:
                        - gcc
                        - clang-3.8
                        - automake autoconf libtool libssl-dev graphviz mscgen
                        - libconfig-dev
                        - codespell
                        - libpcap-dev
                        - libnuma-dev
#        coverity_scan:
#                project:
#                        name: "$TRAVIS_REPO_SLUG"
#                        notification_email: xxxx
#                        build_command_prepend: "./bootstrap && ./configure --enable-test-cpp --enable-test-vald --enable-test-helper --enable-test-perf --enable-user-guides --enable-test-perf-proc --enable-test-example"
#                        build_command:   "make"
#                        branch_pattern: coverity_scan

cache:
        ccache: true
        pip: true
        directories:
                - dpdk
                - netmap
                - $HOME/cunit-install
                - $HOME/doxygen-install

env:
    global:
        #
        # By default Linaro CODECOV_TOKEN token is used. It's ok to use it to see
        # for individual commit validation. But you you want to track tests history
        # you need generated new one at https://codecov.io specific for your repo.
        - CODECOV_TOKEN=a733c34c-5f5c-4ff1-af4b-e9f5edb1ab5e
        - DPDK_VERS="17.11.3"
        - DOCKER_NAMESPACE="lngodp"
    matrix:
        - CONF=""
        - CONF="--disable-abi-compat"
        - CONF="--enable-deprecated"
        - CONF="--enable-dpdk-zero-copy"
        - CONF="--disable-static-applications"
        - CONF="--disable-host-optimization"
        - CONF="--disable-host-optimization --disable-abi-compat"
        - CONF="--enable-pcapng-support"
        - CONF="--without-openssl"
        - DPDK_SHARED="y" CONF="--disable-static-applications"

compiler:
        - gcc
        - clang

install:
        - sudo apt-get install linux-headers-`uname -r`
script:
        - if [ "${CC#clang}" != "${CC}" ] ; then LD=ld CXX=clang++; fi
        - if [ -n "${CROSS_ARCH}" ] ; then
               docker run  -i -t -v `pwd`:/odp -v /lib/modules:/lib/modules -v /usr/src:/usr/src
                 -e CC="${CC}" -e LD="${LD}" -e CXX="${CXX}"
                 -e CONF="${CONF}" -e DPDK_SHARED="${DPDK_SHARED}"
                 lngodp/odp_ubuntu_14.04.5  /root/build_${CROSS_ARCH}.sh ;
          else
               docker run --privileged -i -t
                 -v `pwd`:/odp -v/lib/modules:/lib/modules -v/usr/src:/usr/src --shm-size 8g
                 -e CC="${CC}" -e LD="${LD}" -e CXX="${CXX}"
                 -e CONF="${CONF}" -e DPDK_SHARED="${DPDK_SHARED}"
                 ${DOCKER_NAMESPACE}/travis-odp-lng-x86 /odp/scripts/ci/build_x86_64.sh $CONF ;
          fi
jobs:
        include:
                - stage: test
                  env: TEST=coverage
                  compiler: gcc
                  script:
                          - docker run --privileged -i -t
                              -v `pwd`:/odp -v /lib/modules:/lib/modules -v /usr/src:/usr/src --shm-size 8g
                              -e CODECOV_TOKEN="${CODECOV_TOKEN}"
                              -e CC="${CC}" -e LD="${LD}" -e CXX="${CXX}"
                              -e CONF="${CONF}"
                              ${DOCKER_NAMESPACE}/travis-odp-lng-x86 /odp/scripts/ci/coverage.sh
                - stage: test
                  env: TEST=distcheck
                  compiler: gcc
                  script:
                          - docker run --privileged -i -t
                              -v `pwd`:/odp -v /lib/modules:/lib/modules -v /usr/src:/usr/src --shm-size 8g
                              -e CC="${CC}" -e LD="${LD}" -e CXX="${CXX}"
                              -e CONF="${CONF}"
                              ${DOCKER_NAMESPACE}/travis-odp-lng-x86 /odp/scripts/ci/distcheck.sh
                - stage: "build only"
                  env: TEST=doxygen
                  compiler: gcc
                  install:
                          # Updated Doxygen
                        - |
                          if [ ! -f "$HOME/doxygen-install/bin/doxygen" ]; then
                                wget https://github.com/doxygen/doxygen/archive/Release_1_8_13.tar.gz
                                tar xpvf Release_1_8_13.tar.gz
                                pushd doxygen-Release_1_8_13
                                cmake -DCMAKE_INSTALL_PREFIX=$HOME/doxygen-install .
                                make -j $(nproc)
                                make install
                                popd
                          fi
                        - export PATH=$HOME/doxygen-install/bin:$PATH
                  script:
                          - ./bootstrap
                          - ./configure
                          # doxygen does not trap on warnings, check for them here.
                          - make doxygen-doc 2>&1 |tee doxygen.log
                          - |
                             fgrep -rq warning ./doxygen.log
                             if [ $? -eq 0 ]; then
                               false
                             else
                               true
                             fi
                - stage: "build only"
                  env: Ubuntu14.04_arm64
                  compiler: gcc
                  script:
                          - docker run  -i -t -v `pwd`:/odp -v /lib/modules:/lib/modules -v /usr/src:/usr/src
                              lngodp/odp_ubuntu_14.04.5  /root/build_arm64.sh
                - stage: test
                  compiler: gcc
                  env: CROSS_ARCH="arm64"
                - stage: test
                  compiler: clang
                  env: CROSS_ARCH="arm64"
                - stage: test
                  compiler: gcc
                  env: CROSS_ARCH="armhf" CFLAGS="-march=armv7-a"
                - stage: test
                  compiler: clang
                  env: CROSS_ARCH="armhf" CFLAGS="-march=armv7-a"
                - stage: test
                  compiler: gcc
                  env: CROSS_ARCH="powerpc"
                - stage: test
                  compiler: clang
                  env: CROSS_ARCH="powerpc"
                - stage: test
                  compiler: gcc
                  env: CROSS_ARCH="i386"
                  script:
                          - docker run --privileged -i -t
                              -v `pwd`:/odp -v /lib/modules:/lib/modules -v /usr/src:/usr/src
                              -e CC="${CC}" -e LD="${LD}" -e CXX="${CXX}"
                              -e CONF="${CONF}"
                              lngodp/odp_ubuntu_14.04.5_i386 /root/build_${CROSS_ARCH}.sh ;
                - stage: test
                  compiler: clang
                  env: CROSS_ARCH="i386"
                  script:
                          - docker run --privileged -i -t
                              -v `pwd`:/odp -v /lib/modules:/lib/modules -v /usr/src:/usr/src
                              -e CC="${CC}" -e LD="${LD}" -e CXX="${CXX}"
                              -e CONF="${CONF}"
                              lngodp/odp_ubuntu_14.04.5_i386 /root/build_${CROSS_ARCH}.sh ;
                - stage: test
                  compiler: gcc
                  env: CROSS_ARCH="arm64" CONF="--disable-abi-compat"
                - stage: test
                  compiler: clang
                  env: CROSS_ARCH="arm64" CONF="--disable-abi-compat"
                - stage: test
                  compiler: gcc
                  env: CROSS_ARCH="armhf" CFLAGS="-march=armv7-a" CONF="--disable-abi-compat"
                - stage: test
                  compiler: clang
                  env: CROSS_ARCH="armhf" CFLAGS="-march=armv7-a" CONF="--disable-abi-compat"
                - stage: test
                  compiler: gcc
                  env: CROSS_ARCH="powerpc" CONF="--disable-abi-compat"
                - stage: test
                  compiler: clang
                  env: CROSS_ARCH="powerpc" CONF="--disable-abi-compat"
                - stage: test
                  compiler: gcc
                  env: CROSS_ARCH="i386" CONF="--disable-abi-compat"
                  script:
                          - docker run --privileged -i -t
                              -v `pwd`:/odp -v /lib/modules:/lib/modules -v /usr/src:/usr/src
                              -e CC="${CC}" -e LD="${LD}" -e CXX="${CXX}"
                              -e CONF="${CONF}"
                              lngodp/odp_ubuntu_14.04.5_i386 /root/build_${CROSS_ARCH}.sh ;
                - stage: test
                  compiler: clang
                  env: CROSS_ARCH="i386" CONF="--disable-abi-compat"
                  script:
                          - docker run --privileged -i -t
                              -v `pwd`:/odp -v /lib/modules:/lib/modules -v /usr/src:/usr/src
                              -e CC="${CC}" -e LD="${LD}" -e CXX="${CXX}"
                              -e CONF="${CONF}"
                              lngodp/odp_ubuntu_14.04.5_i386 /root/build_${CROSS_ARCH}.sh ;
                - stage: test
                  canfail: yes
                  env: TEST=checkpatch
                  compiler: gcc
                  install:
                          - true
                  script:
                          - echo ${TRAVIS_COMMIT_RANGE};
                          - ODP_PATCHES=`echo ${TRAVIS_COMMIT_RANGE} | sed 's/\.//'`;
                          - ./scripts/ci-checkpatches.sh ${ODP_PATCHES};
        allow_failures:
          - canfail: yes

after_failure:
  - cat config.log
  - find . -name "*.trs" | xargs grep -l '^.test-result. FAIL' | while read trs ; do echo FAILURE detected at $trs; cat ${trs%%.trs}.log ; done
